### ISSUE TITLE
Live editor example

### ISSUE THREAD

**Issue by pvdz** [Stuk/promise-me#1]
This is really cool. Could you make a browser example with a live input-output editor? That way people can play with it and immediately see what's going on! Put it on your website, your blog, or even github pages if you must :)

**Comment by Stuk** [comment]
Hey Peter, I actually put a demo up a few days ago here: http://stuk.github.com/promise-me/

Thanks for reminding me to link it from the readme!

**Comment by pvdz** [comment]
Super, thanks :D
