### ISSUE TITLE
Create client-side build

### ISSUE THREAD

**Issue by pvdz** [Stuk/promise-me#3]
The demo uses a client-side version of this script. Can you publish the build for that? Preferably (for me) including the dependencies. 

The demo has this build embedded in a lot of unrelated code unfortunately.

Thanks!

**Comment by Stuk** [comment]
I'll look in to adding a UMD to make it work for CommonJS and the browser. 

In the mean time you could do what I'm doing and use https://github.com/montagejs/mr and https://github.com/montagejs/mop

**Comment by Stuk** [comment]
I've added the ability to load Promise Me through either `<script>` or require.js (or Mr as above) in v0.0.3. I'm afraid I'm not going to create a bundle with the dependencies as you can create a bundle for your specific needs with mop or require.js optimizer.

**Comment by pvdz** [comment]
Great, thanks :)
